development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: lobsters_dev
 pool: 5
 socket: /var/run/mysqld/mysqld.sock
 username: root
 password:

test:
 adapter: sqlite3
 database: db/test.sqlite3
 pool: 5
 timeout: 5000